'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react';
import customTheme from './theme'; // adjust the import path if necessary
import Navbar from "./Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={customTheme}>
          <ColorModeScript initialColorMode={customTheme.config.initialColorMode} />
          <Navbar />
          <main id="main_content">
            {children}
          </main>
        </ChakraProvider>
      </body>
    </html>
  );
}
